"""add_supplier_category_invoices_payments

Revision ID: 0c9acbd43bcb
Revises: 5a99e3f27393
Create Date: 2026-05-24 14:48:53.412520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0c9acbd43bcb'
down_revision = '5a99e3f27393'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create the new enum types explicitly before any table/column references
    # them. alembic's add_column on a new enum does NOT auto-issue CREATE TYPE.
    supplier_category = postgresql.ENUM('food', 'beverage', 'consumo', name='supplier_category')
    supplier_category.create(op.get_bind(), checkfirst=True)
    payment_method = postgresql.ENUM('bank_transfer', 'check', 'cash', name='payment_method')
    payment_method.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_total > 0', name='ck_invoices_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'invoice_number', name='uq_invoices_supplier_number')
    )
    op.create_index(op.f('ix_invoices_created_by_user_id'), 'invoices', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index('ix_invoices_supplier_date', 'invoices', ['supplier_id', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', postgresql.ENUM('bank_transfer', 'check', 'cash', name='payment_method', create_type=False), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('registered_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(method = 'check' AND check_number IS NOT NULL) OR (method <> 'check' AND check_number IS NULL)", name='ck_payments_check_number_consistency'),
    sa.CheckConstraint('amount_total > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_registered_by_user_id'), 'payments', ['registered_by_user_id'], unique=False)
    op.create_table('invoice_payments',
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', name='uq_invoice_payments_invoice_once')
    )
    op.create_index('ix_invoice_payments_payment', 'invoice_payments', ['payment_id'], unique=False)
    op.add_column('suppliers', sa.Column('category', postgresql.ENUM('food', 'beverage', 'consumo', name='supplier_category', create_type=False), server_default='food', nullable=False))
    # Seed default food cost threshold (32%) — configurable from /impostazioni.
    op.execute(
        "INSERT INTO app_settings (key, value, value_type, description) "
        "VALUES ('food_cost_threshold', '32.00', 'number', "
        "'Soglia %% oltre la quale una categoria food cost viene marcata in allerta') "
        "ON CONFLICT (key) DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM app_settings WHERE key = 'food_cost_threshold'")
    op.drop_column('suppliers', 'category')
    op.drop_index('ix_invoice_payments_payment', table_name='invoice_payments')
    op.drop_table('invoice_payments')
    op.drop_index(op.f('ix_payments_registered_by_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.drop_index('ix_invoices_supplier_date', table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_by_user_id'), table_name='invoices')
    op.drop_table('invoices')
    # Drop the enum types we explicitly created in upgrade.
    op.execute("DROP TYPE IF EXISTS payment_method")
    op.execute("DROP TYPE IF EXISTS supplier_category")
    # ### end Alembic commands ###
