"""add_employee_advances

Revision ID: 5a99e3f27393
Revises: 991629b32a56
Create Date: 2026-05-24 13:46:11.736795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5a99e3f27393'
down_revision = '991629b32a56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # service_kind enum already exists in DB (used by pos_sessions, expenses).
    # create_type=False prevents alembic from re-issuing CREATE TYPE.
    op.create_table('employee_advances',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('service', postgresql.ENUM('lunch', 'dinner', name='service_kind', create_type=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_photo_url', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_in_payroll_month', sa.String(length=7), nullable=True),
    sa.Column('settled_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(settled_at IS NULL AND settled_in_payroll_month IS NULL AND settled_by_user_id IS NULL) OR (settled_at IS NOT NULL AND settled_in_payroll_month IS NOT NULL AND settled_by_user_id IS NOT NULL)', name='ck_employee_advances_settlement_complete'),
    sa.CheckConstraint('amount > 0', name='ck_employee_advances_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settled_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_advances_created_by_user_id'), 'employee_advances', ['created_by_user_id'], unique=False)
    op.create_index('ix_employee_advances_date_service', 'employee_advances', ['date', 'service'], unique=False)
    op.create_index(op.f('ix_employee_advances_settled_by_user_id'), 'employee_advances', ['settled_by_user_id'], unique=False)
    op.create_index(op.f('ix_employee_advances_user_id'), 'employee_advances', ['user_id'], unique=False)
    op.create_index('ix_employee_advances_user_settled', 'employee_advances', ['user_id', 'settled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_advances_user_settled', table_name='employee_advances')
    op.drop_index(op.f('ix_employee_advances_user_id'), table_name='employee_advances')
    op.drop_index(op.f('ix_employee_advances_settled_by_user_id'), table_name='employee_advances')
    op.drop_index('ix_employee_advances_date_service', table_name='employee_advances')
    op.drop_index(op.f('ix_employee_advances_created_by_user_id'), table_name='employee_advances')
    op.drop_table('employee_advances')
    # ### end Alembic commands ###
