"""add_user_payroll_fields_and_work_shifts

Revision ID: 6aadac2f0aa5
Revises: dbacff9a59dc
Create Date: 2026-05-24 15:58:59.789010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aadac2f0aa5'
down_revision = 'dbacff9a59dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_shifts',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours > 0 AND hours <= 12', name='ck_work_shifts_hours_range'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'user_id', name='uq_work_shifts_date_user')
    )
    op.create_index(op.f('ix_work_shifts_created_by_user_id'), 'work_shifts', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_work_shifts_date'), 'work_shifts', ['date'], unique=False)
    op.create_index('ix_work_shifts_user_date', 'work_shifts', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_work_shifts_user_id'), 'work_shifts', ['user_id'], unique=False)
    op.add_column('users', sa.Column('hourly_rate', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('users', sa.Column('weekly_hours_contract', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weekly_hours_contract')
    op.drop_column('users', 'hourly_rate')
    op.drop_index(op.f('ix_work_shifts_user_id'), table_name='work_shifts')
    op.drop_index('ix_work_shifts_user_date', table_name='work_shifts')
    op.drop_index(op.f('ix_work_shifts_date'), table_name='work_shifts')
    op.drop_index(op.f('ix_work_shifts_created_by_user_id'), table_name='work_shifts')
    op.drop_table('work_shifts')
    # ### end Alembic commands ###
