"""daily_summary_cash_lunch

Revision ID: 9173d7455669
Revises: eda965f7aa6c
Create Date: 2026-05-23 22:26:01.154253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9173d7455669'
down_revision = 'eda965f7aa6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_summaries', sa.Column('cash_lunch_above_float', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_summaries', 'cash_lunch_above_float')
    # ### end Alembic commands ###
