"""daily_summary cash_dinner_above_float (drop cash_total_end)

Revision ID: 991629b32a56
Revises: 9173d7455669
Create Date: 2026-05-23 23:24:34.430232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991629b32a56'
down_revision = '9173d7455669'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_summaries', sa.Column('cash_dinner_above_float', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('daily_summaries', 'cash_total_end_of_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_summaries', sa.Column('cash_total_end_of_day', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('daily_summaries', 'cash_dinner_above_float')
    # ### end Alembic commands ###
