"""initial_schema

Revision ID: fedf57c3bd43
Revises: 
Create Date: 2026-05-23 00:59:43.625891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedf57c3bd43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combined_dishes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('whatsapp', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'staff', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'number', 'boolean', 'json', name='app_setting_value_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_app_settings_updated_by_user_id'), 'app_settings', ['updated_by_user_id'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cash_total_end_of_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fiscal_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ipratico_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_float_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('closed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_daily_summaries_closed_by_user_id'), 'daily_summaries', ['closed_by_user_id'], unique=False)
    op.create_table('evening_closes',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_evening_closes_user_id'), 'evening_closes', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('service', sa.Enum('lunch', 'dinner', name='service_kind'), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_photo_url', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_created_by_user_id'), 'expenses', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_table('pos_sessions',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('service', sa.Enum('lunch', 'dinner', name='service_kind'), nullable=False),
    sa.Column('closing_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('closed_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'service', name='uq_pos_sessions_date_service')
    )
    op.create_index(op.f('ix_pos_sessions_closed_by_user_id'), 'pos_sessions', ['closed_by_user_id'], unique=False)
    op.create_table('products',
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('unit_size', sa.String(length=40), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_purchase_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vat_rate', sa.Enum('iva_4', 'iva_5', 'iva_10', 'iva_22', name='vat_rate'), server_default='iva_22', nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('preferred_supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('default_order_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_preferred_supplier_id'), 'products', ['preferred_supplier_id'], unique=False)
    op.create_index('uq_products_code_when_not_null', 'products', ['code'], unique=True, postgresql_where=sa.text('code IS NOT NULL'))
    op.create_table('staff_meals',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('service', sa.Enum('lunch', 'dinner', name='service_kind'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_meals_created_by_user_id'), 'staff_meals', ['created_by_user_id'], unique=False)
    op.create_index('ix_staff_meals_date_service', 'staff_meals', ['date', 'service'], unique=False)
    op.create_table('supplier_orders',
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'received', 'cancelled', name='supplier_order_status'), server_default='draft', nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('whatsapp_message_generated', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_orders_created_at', 'supplier_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_supplier_orders_created_by_user_id'), 'supplier_orders', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_orders_supplier_id'), 'supplier_orders', ['supplier_id'], unique=False)
    op.create_table('batches',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('initial_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_price_unit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('load_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('receipt_photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_created_by_user_id'), 'batches', ['created_by_user_id'], unique=False)
    op.create_index('ix_batches_expiry_date', 'batches', ['expiry_date'], unique=False)
    op.create_index('ix_batches_product_expiry', 'batches', ['product_id', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_batches_product_id'), 'batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_batches_supplier_id'), 'batches', ['supplier_id'], unique=False)
    op.create_table('combined_dish_components',
    sa.Column('combined_dish_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['combined_dish_id'], ['combined_dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combined_dish_components_combined_dish_id'), 'combined_dish_components', ['combined_dish_id'], unique=False)
    op.create_index(op.f('ix_combined_dish_components_product_id'), 'combined_dish_components', ['product_id'], unique=False)
    op.create_table('evening_close_items',
    sa.Column('evening_close_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['evening_close_id'], ['evening_closes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evening_close_items_evening_close_id'), 'evening_close_items', ['evening_close_id'], unique=False)
    op.create_index(op.f('ix_evening_close_items_product_id'), 'evening_close_items', ['product_id'], unique=False)
    op.create_table('staff_meal_items',
    sa.Column('staff_meal_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_meal_id'], ['staff_meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_meal_items_product_id'), 'staff_meal_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_staff_meal_items_staff_meal_id'), 'staff_meal_items', ['staff_meal_id'], unique=False)
    op.create_table('staff_meal_participants',
    sa.Column('staff_meal_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['staff_meal_id'], ['staff_meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_meal_participants_staff_meal_id'), 'staff_meal_participants', ['staff_meal_id'], unique=False)
    op.create_index(op.f('ix_staff_meal_participants_user_id'), 'staff_meal_participants', ['user_id'], unique=False)
    op.create_table('stock_alerts',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('status_signaled', sa.Enum('low', 'out', name='stock_signaled_status'), nullable=False),
    sa.Column('suggested_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signaled_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('open', 'included_in_order', 'ignored', name='stock_alert_status'), server_default='open', nullable=False),
    sa.Column('source', sa.Enum('staff', 'system', name='stock_alert_source'), server_default='staff', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signaled_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_alerts_product_id'), 'stock_alerts', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_alerts_signaled_by_user_id'), 'stock_alerts', ['signaled_by_user_id'], unique=False)
    op.create_table('movements',
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('load', 'sale', 'waste_expiry', 'waste_other', 'adjustment', 'staff_meal', name='movement_type'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_batch_id'), 'movements', ['batch_id'], unique=False)
    op.create_index('ix_movements_product_created', 'movements', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_movements_product_id'), 'movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_movements_user_id'), 'movements', ['user_id'], unique=False)
    op.create_table('supplier_order_lines',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['stock_alerts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['supplier_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_order_lines_alert_id'), 'supplier_order_lines', ['alert_id'], unique=False)
    op.create_index(op.f('ix_supplier_order_lines_order_id'), 'supplier_order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_supplier_order_lines_product_id'), 'supplier_order_lines', ['product_id'], unique=False)
    op.create_index('ix_supplier_order_lines_product_order', 'supplier_order_lines', ['product_id', 'order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_order_lines_product_order', table_name='supplier_order_lines')
    op.drop_index(op.f('ix_supplier_order_lines_product_id'), table_name='supplier_order_lines')
    op.drop_index(op.f('ix_supplier_order_lines_order_id'), table_name='supplier_order_lines')
    op.drop_index(op.f('ix_supplier_order_lines_alert_id'), table_name='supplier_order_lines')
    op.drop_table('supplier_order_lines')
    op.drop_index(op.f('ix_movements_user_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_product_id'), table_name='movements')
    op.drop_index('ix_movements_product_created', table_name='movements')
    op.drop_index(op.f('ix_movements_batch_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_stock_alerts_signaled_by_user_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_product_id'), table_name='stock_alerts')
    op.drop_table('stock_alerts')
    op.drop_index(op.f('ix_staff_meal_participants_user_id'), table_name='staff_meal_participants')
    op.drop_index(op.f('ix_staff_meal_participants_staff_meal_id'), table_name='staff_meal_participants')
    op.drop_table('staff_meal_participants')
    op.drop_index(op.f('ix_staff_meal_items_staff_meal_id'), table_name='staff_meal_items')
    op.drop_index(op.f('ix_staff_meal_items_product_id'), table_name='staff_meal_items')
    op.drop_table('staff_meal_items')
    op.drop_index(op.f('ix_evening_close_items_product_id'), table_name='evening_close_items')
    op.drop_index(op.f('ix_evening_close_items_evening_close_id'), table_name='evening_close_items')
    op.drop_table('evening_close_items')
    op.drop_index(op.f('ix_combined_dish_components_product_id'), table_name='combined_dish_components')
    op.drop_index(op.f('ix_combined_dish_components_combined_dish_id'), table_name='combined_dish_components')
    op.drop_table('combined_dish_components')
    op.drop_index(op.f('ix_batches_supplier_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_product_id'), table_name='batches')
    op.drop_index('ix_batches_product_expiry', table_name='batches')
    op.drop_index('ix_batches_expiry_date', table_name='batches')
    op.drop_index(op.f('ix_batches_created_by_user_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_supplier_orders_supplier_id'), table_name='supplier_orders')
    op.drop_index(op.f('ix_supplier_orders_created_by_user_id'), table_name='supplier_orders')
    op.drop_index('ix_supplier_orders_created_at', table_name='supplier_orders')
    op.drop_table('supplier_orders')
    op.drop_index('ix_staff_meals_date_service', table_name='staff_meals')
    op.drop_index(op.f('ix_staff_meals_created_by_user_id'), table_name='staff_meals')
    op.drop_table('staff_meals')
    op.drop_index('uq_products_code_when_not_null', table_name='products', postgresql_where=sa.text('code IS NOT NULL'))
    op.drop_index(op.f('ix_products_preferred_supplier_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_pos_sessions_closed_by_user_id'), table_name='pos_sessions')
    op.drop_table('pos_sessions')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_by_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_evening_closes_user_id'), table_name='evening_closes')
    op.drop_table('evening_closes')
    op.drop_index(op.f('ix_daily_summaries_closed_by_user_id'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_app_settings_updated_by_user_id'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('expense_categories')
    op.drop_table('combined_dishes')
    # ### end Alembic commands ###
